Created frank mugagga portfolio
FrankMugagga/Mugagga_Frank_Portfolio pull request #1
Opened 2023-01-12 15:20 UTC by FrankMugagga

created an index.html and style.css files

2023-01-13 14:46 UTC, Yerimah requested changes
# STATUS: REQUIRE CHANGES 🔴 ♻️ 

Hi @FrankMugagga, 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b70556d45436b5038554458344c37536b552f67697068792e676966](https://user-images.githubusercontent.com/71140133/212347499-7364fc9c-220b-4c52-9a7b-072f63c9230f.gif)

## Highlights
- GitHub flow ✅ 
- No linter error ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:46 UTC, Yerimah commented on index.html
> +        </header>
- [ ] Good job using the `<header>` tag but as part of the standard practice the logo on the left should be enclosed in a link (`<a>` tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

- [ ]  For this project the hamburger button should be on the right and is wrapped in a `<nav>` tag. The `<nav>` tag is for semantics reasons, and the right position for convention and user experience for mobile devices. Kindly include it. 😊

2023-01-13 14:46 UTC, Yerimah commented on index.html
> +            </div>
- [ ] Kindly change the `h2` tag to `h1`. The main title (e.g., "I'm Marianne ...") is an `h1` tag. This is ideal for semantic reasons and it optimizes your website for SEO.

2023-01-13 14:46 UTC, Yerimah commented on index.html
> +        </main>
- [ ] This whole section should be enclosed in a section tag and the paragraph content should be wrapped in a `p` tag.
- [ ] Secondly, The list of icons should be grouped in a `<ul>` tag, and `<li>` for each icon; each icon has a link (`<a>` tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. Kindly implement these changes.

- [ ] A major requirement for this project is to pick a design from the available Figma template and implement the design to look exactly like your chosen Figma design template but from your work, you haven't met that requirement. Kindly select a template and replicate it.

2023-01-13 14:46 UTC, Yerimah commented on style.css
> +  color: "#6070FF";
- [ ] Please stick to the margins, font size, and design specifications provided in your chosen Figma design template in order to make your design visually appealing.

2023-01-13 14:46 UTC, Yerimah commented on style.css
> +  line-height: 24px;
- [ ] This section should have a proper background image (decorations are always background images, not `img` tags). Please make sure to export the content of the background for your chosen template from Figma to meet the project requirement.

2023-01-14 13:56 UTC, didierganthier reviewed
Hi <STUDENT_MENTION>,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.

<img src="https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif" />

## Invalid Code Review Request 🚫

- You have submitted a project where this branch is conflicting with the main, resulting in the linters check not running 🏃🏽 ✅  kindly resolve the conflicts and request another review. 😉 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

2023-01-14 18:25 UTC, christianbiring1 requested changes
Hi @FrankMugagga , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/212489643-ad7fc55f-bde0-4662-8461-10afd54ca2d0.gif)


 ## Highlights
- [ ] All linters are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 18:25 UTC, christianbiring1 commented on index.html
> +            </div>
- [ ]  as said by the previous reviewer, Kindly make sure your hamburger menu is grabbed inside a navigation `nav` tag for semantic reasons and accessibility to your web for screen readers.
YOu may consider checking this [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav#:~:text=The%20HTML%20element%20represents,tables%20of%20contents%2C%20and%20indexes.) for more info when to use a `nav` tag

2023-01-14 18:25 UTC, christianbiring1 commented on index.html
> +                   <a href="https://venture.angellist.com/v/login"><img src="images/angellist.svg" alt="angellist"></a>
- [ ] For semantic reasons, instead of using a generic `div` kindly make  sure the social icons are grabbed inside a list element `ul` and each one in a `li`

2023-01-14 19:36 UTC, FrankMugagga commented on index.html
> +                   <a href="https://venture.angellist.com/v/login"><img src="images/angellist.svg" alt="angellist"></a>
All the above have been made right

2023-01-16 23:24 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @FrankMugagga  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 23:24 UTC, iambenkis commented on README.md
> +
- [ ] You should customize your README file according to the details of your project, kindly update it :+1: This will make your repo well documented :memo:

2023-01-16 23:24 UTC, iambenkis commented on index.html
> +        </header>
- [ ] Good job making this first page of your portfolio, however :smile: you added this part here that is representing the telephone or an emulator, kindly remove that in order to get a more stocked design :+1: 

![Screenshot from 2023-01-17 01-15-00 (1)](https://user-images.githubusercontent.com/80458199/212778941-e241ec83-0be0-425a-959d-7be91b5ccd32.png)

2023-01-16 23:24 UTC, iambenkis commented on index.html
> +        </nav>
- [ ] Kindly remove this underlined value on the `logo` , if if you check this Figma design, there is no underlining. :100: 

![Screenshot from 2023-01-17 01-18-29](https://user-images.githubusercontent.com/80458199/212779189-c3c6992f-2074-4c40-a030-7dc93e85046c.png)

2023-01-16 23:24 UTC, iambenkis commented on style.css
> +}
- [ ] Good job adding this `LETS CONNECT` text :clap: , but as mentioned in the requirements sticking to the design means to make sure that colors, padding, margin, etc. are the same. Kindly change this requirement according to this Figma template
![Screenshot from 2023-01-17 01-21-24](https://user-images.githubusercontent.com/80458199/212779421-34ccb5fa-af6e-46e5-9abb-44ea67589132.png)

2023-01-18 05:43 UTC, amejid approved these changes
Hi @FrankMugagga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 06:37 UTC, merged

2023-01-18 06:37 UTC, FrankMugagga commented
MERGING THE FIRST PAGE OF THE PHONE PORTFOLIO