Refactored to load dynamically and developed a popup window for projects section
FrankMugagga/Mugagga_Frank_Portfolio pull request #19
Opened 2023-02-10 14:41 UTC by FrankMugagga

I have designed a pop up window for the works section that shows a cards data when the button is clicked and also refactored the cards section to load dynamically when a page shows

2023-02-10 17:44 UTC, DuaneDave requested changes
Hi @FrankMugagga  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good usage of the Es6 syntaxes.
✔️ All linters are passing
✔️ Professional pull request summary


## Required Changes ♻️
- In order to have a well documented projects, please fill up the missing sections of your readme as pointed out in the screenshot.

![readddddd](https://user-images.githubusercontent.com/84930355/218159553-751d844b-e393-44a8-a1b5-678a0481b48d.PNG)


- Also, consider removing the FAQ section since it is optional or add some questions to it if you would wanna keep it.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing the first letter of your commit messages in order to follow the best practices.
- Using a short PR heading  to make it easy to read since the one you are having is quite lengthy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 17:44 UTC, DuaneDave commented on portfolio.js
> +       <div class="snap_cont">
Good job on successfully implementing the popup window. However I notice a little issue with the transparency of your version. On the figma template the card itself is opaque but the backdrop is transluscent but your version is transluscent only both thwee card and the backdrop. I strongly recommend that you fix this as it will improve the UI and the UX of your website tremendously 😄 


YOUR VERSION

![wrong](https://user-images.githubusercontent.com/84930355/218154306-784a9b60-168f-4830-a684-81b85c3ea735.png)


FIGMA DESIGN

![backdrop](https://user-images.githubusercontent.com/84930355/218154360-f5565208-15af-4db8-bf55-9d33e1c997ad.png)


Also, while it is a good idea to get creative it you should not forget that one of the objectives for this module is to learn to stick with a provided template. If you notice the screenshots you'd see that the close button does not match the one on the figma template, kindly update this in order to achieve some consistency in your design and to enforce the discipline of sticking to a provided template,.

2023-02-10 17:44 UTC, DuaneDave commented on portfolio.js
> +          ${dataItem.stack[1]}
[OPTIONAL] I am making this optional because it is not related to the modal but I strongly recommend that you adjust your CSS to ensure that this button does not overflow out of its parent container. Kindly fix this to provide a good Ux and to make the page well organized.


SEE BELOW

![opt](https://user-images.githubusercontent.com/84930355/218156093-a242b10a-886c-4a01-ac76-6c57ff2274a4.PNG)

2023-02-10 17:44 UTC, DuaneDave commented on portfolio.js
> +});
[OPTIONAL] As a good practice for programmers its important to not repeat yourself except unavoidable. Imagine if this page is having 100 buttons, you'd agree with me that it won't be a good idea to write this 100 times, you'd get tired and your codebase becomes difficult to  maintain. Please refactor this using the below to avoid repeating yourself.


First allow the buttons to have the same `Id` after that

````
const popUpButtons = document.querySelctorAll('#btn_one');  //this returns an array of all the buttons found

//loop through the array and add event listeners
popUpButtons.forEach((button, index) => {
  //attach an event listener to each button and make use of the index to render the modal with the corect contents from thee array of objectys.
})

```

2023-02-11 04:53 UTC, Shedrack-Sunday requested changes
Hi @FrankMugagga   👋

CHANGES REQUIRED ♻️
Great work on the project 👏
You've done well implementing the requirements, However, there are a few you need to work on, to move to the next project. 💯


Highlights
✅All linters are checked 🔢 
✅ Descriptive commit messages 👍 
✅ Nice design 🥇 
 

Required Changes ♻️

 - [ ] You did make effort in the Project and you really did a great job  👏 . However, there seem to be a few adjustments needed to be made, based on the design given, to make your whole code stand out and look good. 👍

-  Implementing web accessibility in website design and development benefits developers by increasing the usability and reach of the website, attracting a wider range of users and potential customers. It also demonstrates a commitment to inclusivity and responsible design practices, improving the developer's reputation and potentially reducing the risk of legal consequences. Furthermore, incorporating accessibility considerations can enhance the overall user experience and lead to more positive feedback and engagement.

 Kindly fix the margin on the right of the screen view. good job so far 👏

check the comment section for a detailed review

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-11 04:53 UTC, Shedrack-Sunday commented on portfolio.js
> +       </div>
- [ ] Just as the previous reviewer did make mentioned, kindly fix the transparency issue here which does not ideally give a good user experience 😉 . You can compare it to the figma design which I attached below, to see the difference.
- Web accessibility ensures that people with disabilities can access and use websites and technology, providing equal opportunities and independence. It also benefits everyone by making websites easier to use and more user-friendly, leading to improved user experience and increased engagement. Failing to make websites accessible can result in legal consequences and the exclusion of potential users and customers.

## Your view :
![image](https://user-images.githubusercontent.com/50990925/218240616-f06d2389-42a8-4594-88de-9b052a2c256a.png)


## Figma:
![image](https://user-images.githubusercontent.com/50990925/218240687-84f91785-e27b-4f48-9d66-57d603171a6a.png)

2023-02-11 06:54 UTC, topeogunleye approved these changes
### Hi @FrankMugagga, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good summary description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 07:44 UTC, merged