I added images/Javascript.png and replaced it with images?javascript_…
FrankMugagga/Mugagga_Frank_Portfolio pull request #4
Opened 2023-01-18 10:24 UTC by FrankMugagga

…logo.png which i abblied to the About myself section

2023-01-18 11:15 UTC, KanzaTahreem reviewed
# INVALID ❌ 

Hi @FrankMugagga 👋

While you made a great effort in this project, unfortunately, I still cannot proceed to review your code. 😓

## Invalid Code Review Request ❌

- [ ] Unfortunately, you have submitted a project that is not professional and includes placeholders that are there to guide you and not your reader. We don't want reader to get confused. Right ? 🎯 I think it would be better if you remove these `Describe your project in 1 or 2 sentences.`. **_Please note that this applies to your whole README_**
- [ ] Please make sure that your all linters are passing. Currently, your PR shows 0 checks. Please fix this. I know you can do that 💪


You can take a step back and read the [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more clarity 💡

_**Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready**_ 🤝🙏

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

_**Reviewed By [Kanza Tahreem](https://github.com/KanzaTahreem)**_

2023-01-18 16:07 UTC, OyePriscilla requested changes
Hi @FrankMugagga 😃, 

You've really done a great work, I must confess!

There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github Flow observed✔️
Linters Set up correctly ✔️ 
Descriptive PR summary and title ✔️ 

## Required Changes ♻️

- [ ] **I noticed that you repeated your code from `line 450 to line 551`, I think you suppose to remove it because it is rendering partially on your app interface. Kindly do this to have a great user interface.** 😄.
- [ ] Kindly remove all the placeholders in your README file as suggested earlier; fix the broken logo link if you have one or remove it if not; ensure that your getting started section is properly filled with necessary details. 👍  

## Optional suggestions

[optional] Please always ensure that your commit messages are in imperative tense and capitalized. ℹ️ 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 16:07 UTC, OyePriscilla commented on index.html
> +            </header> -->
- [ ] To make your codebase clean, kindly take your time to remove all commented codes. 👍

2023-01-18 16:07 UTC, OyePriscilla commented on index.html
> +                        </button>
- [ ] Please kindly increase the `padding` of this button element and also ensure to add the correct typography for the button interaction; so that we can have a design close to that of the given template . 👍 

## Figma Design
![png-transparent-nigerian-naira-currency-symbol-symbol-miscellaneous-angle-text](https://user-images.githubusercontent.com/103386183/213219201-0f2ba435-98ac-425c-9f16-6297fe9b113a.png)

**> Note: don't forget to implement this for all the buttons element.**

2023-01-18 16:07 UTC, OyePriscilla commented on index.html
> +        <section class="works_section"> <!--works section-->
- [ ] Kindly implement the appropriate background-color according to the design template.
`background-color: #E5E5E5;`. ℹ️

2023-01-18 18:11 UTC, christianbiring1 commented on index.html
> +            </header> -->
resolved :+1:

2023-01-18 18:19 UTC, christianbiring1 commented on style.css
> +} */
- [ ] As mentioned previously, Kindly make sure all the commented lines of code are removed from your codebase to make your code more readable.

2023-01-18 18:19 UTC, christianbiring1 commented on style.css
> +}
- [ ] As mentioned earlier by the previous reviewer, Kindly make sure all the button interaction styles are implemented. 
`hover`, `active`, and `disable` and that is for all the buttons as it is shown in the Figm template for a better user experience.

2023-01-18 18:19 UTC, christianbiring1 commented on index.html
> +                        </button>
Not resolved :red_circle:

2023-01-18 18:22 UTC, christianbiring1 requested changes
Hi @FrankMugagga , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/213262963-942be52b-aa35-46be-9b66-4aeb62bdcc86.gif)


 ## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 18:22 UTC, christianbiring1 commented on style.css
> +  /* position: absolute; */
- [ ] As mentioned previously, Kindly make sure all the commented lines of code are removed from your codebase to make your code more readable.

2023-01-19 09:42 UTC, Owusu-Desmond approved these changes
Hi @FrankMugagga , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 09:42 UTC, Owusu-Desmond commented on index.html
> +                    </div>
- [ OPTIONAL ] Please note that the list of languages is not supposed to be here. 
### you have this
![Screenshot from 2023-01-19 09-36-28](https://user-images.githubusercontent.com/92303891/213407445-d57e28dc-fbdd-4a6a-ac97-9d27894cce58.png)

### it is supposed to be this
![Screenshot from 2023-01-19 09-33-03](https://user-images.githubusercontent.com/92303891/213407270-d69b8494-eec1-43de-8f0c-e455927abd00.png)

2023-01-19 09:42 UTC, Owusu-Desmond commented on index.html
> +                        </ul>
- [ OPTIONAL ] Please make sure that you implement this optional suggestion since it is important. This list of languages is not supposed to be here but you have it here.
### You have this
![Screenshot from 2023-01-19 09-37-47](https://user-images.githubusercontent.com/92303891/213408528-79fab835-7814-42d9-882d-b666c46c8bc3.png)

### It is supposed to be this.
![Screenshot from 2023-01-19 09-41-09](https://user-images.githubusercontent.com/92303891/213408464-f6a8783b-9ac9-46c0-8d2f-86bc690f2c8e.png)

2023-01-19 14:21 UTC, merged