Portfolio_resposnsive_web_design
FrankMugagga/Mugagga_Frank_Portfolio pull request #8
Opened 2023-01-26 07:20 UTC by FrankMugagga

I have added media queries to make the site responsive for all devices

2023-01-26 20:10 UTC, binhussen requested changes
Hi @FrankMugagga , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 20:10 UTC, binhussen commented on style.css
> +  }
- Kindly, your header `nav` and `logo` needs some space from the edges and your background image and space between text need some modification to stick the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=ATtHEbgnesfQooGE-0), please fix it 👌👍
👇


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/214935883-c30150dd-5800-4b35-8556-08b8f9ce4d19.png" width="600">|<img src="https://user-images.githubusercontent.com/52010789/214936013-d8a60af2-7e6c-4be7-b011-65d01fd01981.png" width="600">|


😎️

🤝️

2023-01-26 20:10 UTC, binhussen commented on style.css
> +  }
- Kindly, your cards need some space between text and font update to stick the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=ATtHEbgnesfQooGE-0), please fix it 👌

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/214936781-cf23e21d-abbb-4dcc-9bd1-a816d7eb80ab.png" width="600">|<img src="https://user-images.githubusercontent.com/52010789/214936775-b7ec9b76-1bb9-4860-8ed2-ddcf07a6bc0d.png" width="600">|


😎️

🤝️

2023-01-26 20:10 UTC, binhussen commented on style.css
> +  }
- Great job for trying the design👌👍, however, it needs some changes on content spacing and tech card lists, 👌 please fix it to stick the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=ATtHEbgnesfQooGE-0), please fix it 👌



| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/214937980-b81481b6-9fe4-46fc-bf10-4eadd0f78533.png" width="600">|<img src="https://user-images.githubusercontent.com/52010789/214937985-94b2c96d-ad3f-43e2-923c-d4ff9af609fc.png" width="600">|


😎️

🤝️

2023-01-26 20:10 UTC, binhussen commented on style.css
> +  }
- Kindly, your contact form size needs some size, and background images aren't placed in the exact place as the figma  one 👌👍please fix it to stick the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=ATtHEbgnesfQooGE-0), please fix it 👌



| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/214938893-590b0c1a-f9c8-4813-af9f-987ecbe79089.png" width="600">|<img src="https://user-images.githubusercontent.com/52010789/214938895-7b0d7359-f1a0-486c-b446-826ae3408014.png" width="600">|


😎️

🤝️

2023-01-26 20:10 UTC, binhussen commented on style.css
> +}
- kindly, both your desktop and mobile version has overflow because giving fixed size, please update it to have a user-friendly UI👌👇

https://user-images.githubusercontent.com/52010789/214939884-4f28b285-8f61-47b9-b44e-43cc212cbdc9.mp4

2023-01-27 18:23 UTC, jasonfelice requested changes
Hi @FrankMugagga, 

Good job implementing the changes requested by @binhussen.
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
No Linter errors✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 18:23 UTC, jasonfelice commented on style.css
> +.card_works_one:hover {
- [ ] I will recommend removing the hover effects from the portfolio cards because it is distorting the content.

![image](https://user-images.githubusercontent.com/92215878/215163749-22ae917e-401c-4a85-b158-86435cbf3965.png)

2023-01-27 18:23 UTC, jasonfelice commented on style.css
- [ ] Please fix the white space on the right side. 😄 

![image](https://user-images.githubusercontent.com/92215878/215164648-024c771d-b6d4-4105-91de-65d851b85488.png)

2023-01-27 20:09 UTC, jerryowusu requested changes
Hi @FrankMugagga  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so close](https://user-images.githubusercontent.com/65233860/215187243-f9311f4e-0b93-40c5-86a6-804128555e14.gif)

 ## Highlights
No linter errors :+1: 
Great effort so far :heavy_check_mark: 

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

- [ ]  Your project does not have any license file, hence the link to the license in the readme is broken, kindly check and fix that. :wink:

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 20:09 UTC, jerryowusu commented on style.css
> +  h1 {
As requested by the previous reviewer, kindly fix the white blank space that appears to the right side of the page to give your project a more responsive appealing. :pray

![Screenshot from 2023-01-27 20-00-34](https://user-images.githubusercontent.com/65233860/215186784-374d9c7f-06df-4e3a-9730-0f2fd7db5cdb.png)

2023-01-27 20:12 UTC, FrankMugagga commented
Please make me understand what I mean. I put a border and besides, I have
only implemented as seen in figma

On Fri, Jan 27, 2023, 11:09 PM Jerry Owusu ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @FrankMugagga <https://github.com/FrankMugagga>
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> [image: so close]
> <https://user-images.githubusercontent.com/65233860/215187243-f9311f4e-0b93-40c5-86a6-804128555e14.gif>
> Highlights
>
> No linter errors 👍
> Great effort so far ✔️
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
>    - Your project does not have any license file, hence the link to the
>    license in the readme is broken, kindly check and fix that. 😉
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#discussion_r1089382748>
> :
>
> > ***@***.*** screen and (min-width: 786px) {
>
> +  .phone_template {
>
> +    width: 1440px;
>
> +  }
>
> +
>
> +  .head_template {
>
> +    width: 1435px;
>
> +    height: 916px;
>
> +    background-size: cover;
>
> +    border-bottom-left-radius: 100px;
>
> +  }
>
> +
>
> +  .app_head_nav {
>
> +    width: 1350px;
>
> +    height: 72px;
>
> +    padding-left: 142px;
>
> +    padding-right: 142px;
>
> +  }
>
> +
>
> +  .logo {
>
> +    top: 16px;
>
> +    left: 143px;
>
> +  }
>
> +
>
> +  .sidebut {
>
> +    display: none;
>
> +  }
>
> +
>
> +  .item_nav {
>
> +    display: flex;
>
> +    flex-direction: row;
>
> +    align-items: center;
>
> +    justify-content: space-around;
>
> +    padding: 1px;
>
> +    gap: 8px;
>
> +    width: 259px;
>
> +    height: 40px;
>
> +    left: 1039px;
>
> +  }
>
> +
>
> +  .items {
>
> +    width: 63px;
>
> +    height: 20px;
>
> +    font-family: 'Poppins', sans-serif;
>
> +    font-style: normal;
>
> +    font-weight: 500;
>
> +    font-size: 15px;
>
> +    line-height: 20px;
>
> +    display: flex;
>
> +    align-items: center;
>
> +    text-align: center;
>
> +    color: #344563;
>
> +    flex: none;
>
> +    order: 0;
>
> +    flex-grow: 0;
>
> +  }
>
> +
>
> +  .main {
>
> +    padding-left: 260px;
>
> +    padding-right: 260px;
>
> +    padding-top: 200px;
>
> +    padding-bottom: 255px;
>
> +    width: 1435px;
>
> +    background: url("images/Header_deskV.png");
>
> +    background-size: 1290px;
>
> +    background-repeat: no-repeat;
>
> +  }
>
> +
>
> +  h1 {
>
>
> As requested by the previous reviewer, kindly fix the white blank space
> that appears to the right side of the page to give your project a more
> responsive appealing. :pray
>
> [image: Screenshot from 2023-01-27 20-00-34]
> <https://user-images.githubusercontent.com/65233860/215186784-374d9c7f-06df-4e3a-9730-0f2fd7db5cdb.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#pullrequestreview-1273394400>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HU4OIRAQSHLA5JRWVEKT3WUQTOVANCNFSM6AAAAAAUHFUVIY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-27 20:15 UTC, FrankMugagga commented
Please advise me on exactly what that means I have added a border. That was
my last request

On Fri, Jan 27, 2023, 11:12 PM mugagga frank ***@***.***>
wrote:

> Please make me understand what I mean. I put a border and besides, I have
> only implemented as seen in figma
>
> On Fri, Jan 27, 2023, 11:09 PM Jerry Owusu ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @FrankMugagga <https://github.com/FrankMugagga>
>>
>> Great work on making the changes requested by a previous reviewer 👏
>> You've done well implementing some of the requested changes, but there
>> are still some which aren't addressed yet.
>>
>> [image: so close]
>> <https://user-images.githubusercontent.com/65233860/215187243-f9311f4e-0b93-40c5-86a6-804128555e14.gif>
>> Highlights
>>
>> No linter errors 👍
>> Great effort so far ✔️
>> Required Changes ♻️
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>>    - Your project does not have any license file, hence the link to the
>>    license in the readme is broken, kindly check and fix that. 😉
>>
>> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
>> PR. However, I strongly recommend you to take them into account as they can
>> make your code better. Some of them were simply missed by the previous
>> reviewer and addressing them will really improve your application.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In style.css
>> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#discussion_r1089382748>
>> :
>>
>> > ***@***.*** screen and (min-width: 786px) {
>>
>> +  .phone_template {
>>
>> +    width: 1440px;
>>
>> +  }
>>
>> +
>>
>> +  .head_template {
>>
>> +    width: 1435px;
>>
>> +    height: 916px;
>>
>> +    background-size: cover;
>>
>> +    border-bottom-left-radius: 100px;
>>
>> +  }
>>
>> +
>>
>> +  .app_head_nav {
>>
>> +    width: 1350px;
>>
>> +    height: 72px;
>>
>> +    padding-left: 142px;
>>
>> +    padding-right: 142px;
>>
>> +  }
>>
>> +
>>
>> +  .logo {
>>
>> +    top: 16px;
>>
>> +    left: 143px;
>>
>> +  }
>>
>> +
>>
>> +  .sidebut {
>>
>> +    display: none;
>>
>> +  }
>>
>> +
>>
>> +  .item_nav {
>>
>> +    display: flex;
>>
>> +    flex-direction: row;
>>
>> +    align-items: center;
>>
>> +    justify-content: space-around;
>>
>> +    padding: 1px;
>>
>> +    gap: 8px;
>>
>> +    width: 259px;
>>
>> +    height: 40px;
>>
>> +    left: 1039px;
>>
>> +  }
>>
>> +
>>
>> +  .items {
>>
>> +    width: 63px;
>>
>> +    height: 20px;
>>
>> +    font-family: 'Poppins', sans-serif;
>>
>> +    font-style: normal;
>>
>> +    font-weight: 500;
>>
>> +    font-size: 15px;
>>
>> +    line-height: 20px;
>>
>> +    display: flex;
>>
>> +    align-items: center;
>>
>> +    text-align: center;
>>
>> +    color: #344563;
>>
>> +    flex: none;
>>
>> +    order: 0;
>>
>> +    flex-grow: 0;
>>
>> +  }
>>
>> +
>>
>> +  .main {
>>
>> +    padding-left: 260px;
>>
>> +    padding-right: 260px;
>>
>> +    padding-top: 200px;
>>
>> +    padding-bottom: 255px;
>>
>> +    width: 1435px;
>>
>> +    background: url("images/Header_deskV.png");
>>
>> +    background-size: 1290px;
>>
>> +    background-repeat: no-repeat;
>>
>> +  }
>>
>> +
>>
>> +  h1 {
>>
>>
>> As requested by the previous reviewer, kindly fix the white blank space
>> that appears to the right side of the page to give your project a more
>> responsive appealing. :pray
>>
>> [image: Screenshot from 2023-01-27 20-00-34]
>> <https://user-images.githubusercontent.com/65233860/215186784-374d9c7f-06df-4e3a-9730-0f2fd7db5cdb.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#pullrequestreview-1273394400>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A4HU4OIRAQSHLA5JRWVEKT3WUQTOVANCNFSM6AAAAAAUHFUVIY>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***
>> com>
>>
>

2023-01-27 20:30 UTC, FrankMugagga commented
Mr. Jerry am sorry but you didn't make me understand

On Fri, Jan 27, 2023, 11:14 PM mugagga frank ***@***.***>
wrote:

> Please advise me on exactly what that means I have added a border. That
> was my last request
>
> On Fri, Jan 27, 2023, 11:12 PM mugagga frank ***@***.***>
> wrote:
>
>> Please make me understand what I mean. I put a border and besides, I have
>> only implemented as seen in figma
>>
>> On Fri, Jan 27, 2023, 11:09 PM Jerry Owusu ***@***.***>
>> wrote:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> Hi @FrankMugagga <https://github.com/FrankMugagga>
>>>
>>> Great work on making the changes requested by a previous reviewer 👏
>>> You've done well implementing some of the requested changes, but there
>>> are still some which aren't addressed yet.
>>>
>>> [image: so close]
>>> <https://user-images.githubusercontent.com/65233860/215187243-f9311f4e-0b93-40c5-86a6-804128555e14.gif>
>>> Highlights
>>>
>>> No linter errors 👍
>>> Great effort so far ✔️
>>> Required Changes ♻️
>>>
>>> *Check the comments under the review.*
>>> Optional suggestions
>>>
>>>    - Your project does not have any license file, hence the link to the
>>>    license in the readme is broken, kindly check and fix that. 😉
>>>
>>> *Every comment with the [OPTIONAL] prefix won't stop the approval of
>>> this PR. However, I strongly recommend you to take them into account as
>>> they can make your code better. Some of them were simply missed by the
>>> previous reviewer and addressing them will really improve your application.*
>>>
>>> Cheers and Happy coding!👏👏👏
>>>
>>> Feel free to leave any questions or comments in the PR thread if
>>> something is not 100% clear.
>>> Please, remember to tag me in your question so I can receive the
>>> notification.
>>>
>>> *Please, do not open a new Pull Request for re-reviews. You should use
>>> the same Pull Request submitted for the first review, either valid or
>>> invalid unless it is requested otherwise.*
>>> ------------------------------
>>>
>>> *As described in the Code reviews limits policy
>>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>>> limited number of reviews per project (check the exact number in your
>>> Dashboard). If you think that the code review was not fair, you can request
>>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>> ------------------------------
>>>
>>> In style.css
>>> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#discussion_r1089382748>
>>> :
>>>
>>> > ***@***.*** screen and (min-width: 786px) {
>>>
>>> +  .phone_template {
>>>
>>> +    width: 1440px;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .head_template {
>>>
>>> +    width: 1435px;
>>>
>>> +    height: 916px;
>>>
>>> +    background-size: cover;
>>>
>>> +    border-bottom-left-radius: 100px;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .app_head_nav {
>>>
>>> +    width: 1350px;
>>>
>>> +    height: 72px;
>>>
>>> +    padding-left: 142px;
>>>
>>> +    padding-right: 142px;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .logo {
>>>
>>> +    top: 16px;
>>>
>>> +    left: 143px;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .sidebut {
>>>
>>> +    display: none;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .item_nav {
>>>
>>> +    display: flex;
>>>
>>> +    flex-direction: row;
>>>
>>> +    align-items: center;
>>>
>>> +    justify-content: space-around;
>>>
>>> +    padding: 1px;
>>>
>>> +    gap: 8px;
>>>
>>> +    width: 259px;
>>>
>>> +    height: 40px;
>>>
>>> +    left: 1039px;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .items {
>>>
>>> +    width: 63px;
>>>
>>> +    height: 20px;
>>>
>>> +    font-family: 'Poppins', sans-serif;
>>>
>>> +    font-style: normal;
>>>
>>> +    font-weight: 500;
>>>
>>> +    font-size: 15px;
>>>
>>> +    line-height: 20px;
>>>
>>> +    display: flex;
>>>
>>> +    align-items: center;
>>>
>>> +    text-align: center;
>>>
>>> +    color: #344563;
>>>
>>> +    flex: none;
>>>
>>> +    order: 0;
>>>
>>> +    flex-grow: 0;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  .main {
>>>
>>> +    padding-left: 260px;
>>>
>>> +    padding-right: 260px;
>>>
>>> +    padding-top: 200px;
>>>
>>> +    padding-bottom: 255px;
>>>
>>> +    width: 1435px;
>>>
>>> +    background: url("images/Header_deskV.png");
>>>
>>> +    background-size: 1290px;
>>>
>>> +    background-repeat: no-repeat;
>>>
>>> +  }
>>>
>>> +
>>>
>>> +  h1 {
>>>
>>>
>>> As requested by the previous reviewer, kindly fix the white blank space
>>> that appears to the right side of the page to give your project a more
>>> responsive appealing. :pray
>>>
>>> [image: Screenshot from 2023-01-27 20-00-34]
>>> <https://user-images.githubusercontent.com/65233860/215186784-374d9c7f-06df-4e3a-9730-0f2fd7db5cdb.png>
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/FrankMugagga/Mugagga_Frank_Portfolio/pull/8#pullrequestreview-1273394400>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/A4HU4OIRAQSHLA5JRWVEKT3WUQTOVANCNFSM6AAAAAAUHFUVIY>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***
>>> com>
>>>
>>

2023-01-28 15:39 UTC, huseyinbiyik approved these changes
Hi @FrankMugagga,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- Please make sure that your mobile version working fine. You have a big amount of horizontal overflow on mobile version, try to fix it. Check the gif below.
![Screen Recording 2023-01-28 at 6 33 07 PM](https://user-images.githubusercontent.com/25887253/215275344-6dab2768-3be1-4380-9b65-3453fa7c9722.gif)

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 15:39 UTC, huseyinbiyik commented on index.html
> +
[OPTIONAL] Good job with the fixing the white space but please remove this whitespace as well.
<img width="1440" alt="Screenshot 2023-01-28 at 6 29 58 PM" src="https://user-images.githubusercontent.com/25887253/215275432-17de1cde-d9ac-4fa9-8dba-e3ce2f46bf0d.png">

2023-01-28 15:45 UTC, merged